<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilo.css">
    <title>Biblioteca</title>
</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light ">
            <div class="container-fluid ">
                <a class="navbar-brand" href="">BIBLIOTECA VIRTUAL</a>

                <?php if ($this->usuario): ?>
                    <span class="navbar-text"><?= 'Bienvenido ' . $this->usuario->usuario ?></span>    
                <?php else: ?>
                    <a class="navbar-brand" href="<?= BASE_URL . 'mostrar-libros/' ?>">Biblioteca</a>
                <?php endif; ?>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">

                        <?php if ($this->usuario): // Login del usuario 
                        ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'listar-libros/' ?>">Libros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'agregar-libro/' ?>">Agregar Libro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'listar-generos/' ?>">Géneros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'agregar-genero/' ?>">Agregar Género</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'logout/' ?>">Cerrar sesión</a>
                            </li>
                        <?php else: // Si el usuario no está logueado 
                        ?>

                            
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'mostrar-libros/' ?>">Libros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'mostrar-generos/' ?>">Géneros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'login/' ?>">Iniciar sesión</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
</header>

