<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca</title>
    <link rel="stylesheet" href="../css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light ">
            <div class="container-fluid ">


                <?php if ($this->usuario): ?>
                    <a class="navbar-brand" href="">Biblioteca</a>
                    <span class="navbar-text"><?= 'Bienvenido ' . $this->usuario->usuario ?></span>    
                <?php else: ?>
                    <a class="navbar-brand" href="<?= BASE_URL . 'mostrar-libros/' ?>">Biblioteca</a>
                <?php endif; ?>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">

                        <?php if ($this->usuario): // Login del usuario 
                        ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'listar-libros/' ?>">Listar Libros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'agregar-libro/' ?>">Nuevo Libro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'listar-generos/' ?>">Listar Géneros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'agregar-genero/' ?>">Nuevo Género</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'logout/' ?>">Cerrar sesión</a>
                            </li>
                        <?php else: // Si el usuario no está logueado 
                        ?>

                            
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'mostrar-libros/' ?>">Libros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'mostrar-generos/' ?>">Géneros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= BASE_URL . 'login/' ?>">Iniciar sesión</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


