<?php require 'templates/layouts/header.phtml'?>

<div class="container">
    <h1><?= $genero ? 'Editar' : 'Agregar' ?> Genero</h1>
    <form action="<?= $genero ? BASE_URL . 'editar-genero/' . $genero->ID_genero : BASE_URL . 'agregar-genero/' ?>" method="POST">

    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="Nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="form-group">
            <label>Descripción</label>
            <textarea name="Descripcion" class="form-control" rows="3"></textarea>

        <div class="form-group">
            <label>Géneros relacionados</label>
            <textarea name="Relacionado" class="form-control" rows="3"></textarea>

      
        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>
<?php require 'templates/layouts/footer.phtml'?>