<?php require 'templates/layouts/header.phtml'; ?>

<div class="container">
    <h1><?= $libro ? 'Editar' : 'Agregar' ?> Libro</h1>

    <form action="<?= $libro ? BASE_URL . 'editar-libro/' . $libro->ID_libro : BASE_URL . 'agregar-libro/' ?>" method="POST">

        <div class="mb-3">
            <label for="Titulo" class="form-label">Título</label>
            <input type="text" class="form-control" name="Titulo" value="<?= htmlspecialchars($libro ? $libro->Titulo : '') ?>">
        </div>

        <div class="mb-3">
            <label for="Autor" class="form-label">Autor</label>
            <input type="text" class="form-control" name="Autor" value="<?= htmlspecialchars($libro ? $libro->Autor : '') ?>">
        </div>

        <div class="mb-3">
            <label for="Reseña" class="form-label">Reseña</label>
            <input type="text" class="form-control" name="Reseña" value="<?= htmlspecialchars($libro ? $libro->Reseña : '') ?>">
        </div>

        <div class="mb-3">
            <label for="Año" class="form-label">Año de Publicación</label>
            <input type="number" class="form-control" name="Año" value="<?= htmlspecialchars($libro ? $libro->Año : '') ?>">
        </div>

        <div class="mb-3">
            <label for="ID_genero" class="form-label">Género</label>
            <select name="ID_genero" class="form-select">
                <?php foreach ($generos as $genero) : ?>
                    <option value="<?= htmlspecialchars($genero->ID_genero) ?>" <?= $libro && $libro->ID_genero == $genero->ID_genero ? 'selected' : '' ?>>
                        <?= htmlspecialchars($genero->Nombre) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <button type="submit" class="btn btn-success">Enviar</button>
    </form>
</div>

<?php require 'templates/layouts/footer.phtml'; ?>


