<?php require 'templates/layouts/header.phtml'; ?>

<div class="container">
    <h1><?= $libro ? 'Editar' : 'Agregar' ?> Libro</h1>

    <form action="<?= $libro ? BASE_URL . 'editar-libro/' . $libro->ID_libro : BASE_URL . 'agregar-libro/' ?>" method="POST">

    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título</label>
                <input required name="Titulo" type="text" class="form-control" value="<?=$libro ? $libro->Titulo : ''?>">
                </div>
            </div>
        </div>

    <div class="form-group">
        <label>Autor</label>
        <input type="text" class="form-control" name="Autor" value="<?= $libro ? $libro->Autor : '' ?>">
    </div>
     

    <div class="form-group">
        <label>Reseña</label>
        <input type="text" class="form-control" name="Reseña" value="<?= $libro ? $libro->Reseña : '' ?>">
        </div>
    </div>

    <div class="form-group">
        <label>Año</label>
        <input type="text" class="form-control" name="Año" value="<?= $libro ? $libro->Año : '' ?>">
        </div>
    </div>

        
    <div class="form-group">
        <label for="ID_genero">Género</label>
        <select id="ID_genero" name="ID_genero" class="form-select">
            <?php foreach ($generos as $genero): ?>
                <option value="<?= $genero->ID_genero ?>" <?= $libro && $libro->ID_genero == $genero->ID_genero ? 'selected' : '' ?>>
                    <?=($genero->Nombre) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>