<?php require 'templates/layouts/header.phtml' ?>

<div class="container">
    <h2 class="pb-4">Generos</h2>
        <ul class="list-group mt-4">
        <?php foreach($generos as $genero): ?>
           <li class="list-group-item item-task">
                <div class="label">
                    <b><?=$genero->Nombre?> | <?=$genero->Descripcion ?>| <?=$genero->Relacionado ?> | </b>  
                     
                </div>
                
                <div class="actions">
                    <a href="<?= BASE_URL.'editar-genero/'. $genero->ID_genero ?>" type="button" class='btn btn-success btn-sm ml-auto'>Editar</a>
                    <a href="<?=BASE_URL.'eliminar-genero/'. $genero->ID_genero ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Eliminar</a>
                
                </div>
            </li>
        <?php endforeach ?>
        </ul>
</div>

<?php require 'templates/layouts/footer.phtml'?>
