<?php require 'templates/layouts/header.phtml'?>

<div class="container">
    <h2 class="pb-4">Libros</h2>
    <div class="row row-cols-md-4 g-4">
        <?php 
            foreach($libros as $libro): ?>
            <div class="card p-0 col-lg-4 col-md-6 col-sm-12">
                    <div class="card-body card-libro ">
                        <h5 class="card-title m-0"><?= $libro->Titulo ?></h5>
                        <h6 class="card-subtitle mt-3"><?= $libro->Autor ?></h6>
                        <h6 class="card-subtitle mt-3"><?= $libro->Reseña ?></h6>
                        <h6 class="card-subtitle mt-3"><?= $libro->Año ?></h6>
                        <h6 class="card-subtitle mt-3"><?= $libro->genero->Nombre ?></h6>
                    </div>
                    <a href="<?= BASE_URL . 'mostrar-libro' . $libro->ID_libro ?>"  class="btn btn-primary m-3 w-50">Ver más</a> 
                    
            </div>
        <?php 
        endforeach ?>
    </div> 
</div>

<?php require 'templates/layouts/footer.phtml'?>