<?php require 'templates/layouts/header.phtml'; ?>

<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action"><h2>Generos</h2></a>
        <?php foreach ($generos as $genero): ?>

    <div class="actions">
        <a href="<?= BASE_URL . 'mostrar-genero/' . $genero->ID_genero ?>" class="list-group-item list-group-item-action list-group-item-primary"><?= $genero->Nombre ?> <br> Ver Descricion </br></a>
    </div>
        <?php endforeach; ?>
</div>
<?php require 'templates/layouts/footer.phtml'; ?>