<?php require 'templates/layouts/header.phtml'; ?>

<div class="container">
    <h2>Géneros</h2>
    <ul class="list-group">
        <?php foreach ($generos as $genero): ?>
            <li class="list-group-item m-2 item-genero">
                <div class="container-fluid">
                    <a href="<?= BASE_URL . 'mostrar-genero/' . $genero->ID_genero ?>" class="fs-2 m-2">
                        <?= htmlspecialchars($genero->Nombre) ?>
                    </a>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php require 'templates/layouts/footer.phtml'; ?>
