<?php require 'templates/layouts/header.phtml'; ?>

<div class="container">
    <h2>Género</h2>
    <ul class="list-group">
        <?php if (isset($genero) && $genero !== false): ?>
            <li class="list-group-item m-2 item-genero">
                <div class="container-fluid">
                    <a href="<?= BASE_URL . 'libro-genero/' . $genero->ID_genero ?>" class="fs-2 m-2"><?= htmlspecialchars($genero->Nombre) ?></a>
                </div>
            </li>
        <?php else: ?>
            <li class="list-group-item m-2">No se encontró información sobre este género.</li>
        <?php endif; ?>
    </ul>
</div>

<?php require 'templates/layouts/footer.phtml'; ?>
