<?php require 'templates/layouts/header.phtml'?>

<div class="list-group">
<?php if ($genero): ?>
  <ul class="list-group">
    <li class="list-group-item"><h2><?= $genero->Nombre ?></h2></li>
    <li class="list-group-item list-group-item-primary"><b><?=$genero->Nombre?> </b></li>
    <li class="list-group-item list-group-item-secondary"><b><?=$genero->Descripcion ?> </b></li>
    <li class="list-group-item list-group-item-success"><h6>Genero relacionado</h6><?= $genero->Relacionado ?></b></li>
  </ul>    
<div class="actions"> 
  <a href="<?= BASE_URL . 'libro-genero/' . $genero->ID_genero ?>" class="list-group-item list-group-item-action list-group-item-success">Libros por genero</a>
  <?php else: ?>
    <p>Género no encontrado.</p>
  <?php endif; ?> 
</div>
<?php require 'templates/layouts/footer.phtml'?>