<?php require 'templates/layouts/header.phtml'?>

<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body mt-5">
                    <h2><?= $libro->Titulo ?></h2>
                    <p><span>Autor: </span><?= $libro->Autor ?></p>
                    <p><span>Reseña: </span><?= $libro->Reseña ?></p>
                    <p><span>Año de publicación: </span><?= $libro->Año ?></p>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require 'templates/layouts/footer.phtml'?>